### ISSUE TITLE
support desktop, needs to show on mouse hover

### ISSUE THREAD

**Issue by sgehrman** [marcelogil/el_tooltip#11]
I was hoping to use this.  I'm using just_the_tooltip, but having some crashes.

Needs to show after duration when mouse hovers over item.

**Comment by benPesso** [comment]
@sgehrman You could wrap the widget in a [`MouseRegion`](https://api.flutter.dev/flutter/widgets/MouseRegion-class.html) and use `onEnter` and `onExit` to show/hide the tooltip using an `ElTooltipController` controller.
