### ISSUE TITLE
Strange gap between tooltip and arrow

### ISSUE THREAD

**Issue by rostopira** [marcelogil/el_tooltip#17]
![bug](https://github.com/marcelogil/el_tooltip/assets/16724952/4b1a59a1-5878-4a0b-84de-4448d87687d2)

**Comment by marcelogil** [comment]
Hello @rostopira 
In which screen/device did you get this error?

**Comment by rostopira** [comment]
> Hello @rostopira 
> In which screen/device did you get this error?

On Pixel 7 and iPhone 12 Pro

**Comment by marcelogil** [comment]
Hello @rostopira 

Sorry for the late reply.
I believe the issue was with the AntiAlias when drawing the triangle.
It should be fixed now on the new version 2.2.0.

Please let me know if you continue to see it.
