### ISSUE TITLE
Tooltip Disappears Instantly on iOS in el_tooltip Library

### ISSUE THREAD

**Issue by aboodma** [marcelogil/el_tooltip#18]
Hello,

I hope this message finds you well. I am writing to report an issue I have encountered while using the el_tooltip library on iOS. When I click on a tooltip, it disappears instantly, making it challenging to interact with the content.

Steps to Reproduce:

    Include el_tooltip library in an iOS project.
    Trigger the appearance of a tooltip by click on it.
    Observe that the tooltip disappears immediately upon clicking.

Expected Behavior:
The tooltip should remain visible and responsive to user interactions until explicitly closed by the user.

Actual Behavior:
The tooltip disappears instantly upon clicking, hindering the ability to interact with its content.

Environment:

    iOS version: 17.2.1
    el_tooltip version: ^2.0.0
 

Additional Information:
Include any additional details, code snippets, or context that might help the developers understand and reproduce the issue.

Thank you for your attention to this matter, and I appreciate your efforts in maintaining and improving the el_tooltip library.

Best regards,

**Comment by TilTuesday** [comment]
ok

**Comment by appinteractive** [comment]
@aboodma could you solve that issue? I have the same problem and can't figure it out.

**Comment by appinteractive** [comment]
@marcelogil after debugging the show and hide methods, I can see, that the hide method is called immediately after show, hiding the tooltip when trying to show it via the controller while `showModal` is true. 

It's triggered by the `didChangeMetrics` calling `_hideOverlay()` on the `_ElTooltipState`.  To prevent this from happening when the tooltip appears, I introduced a `initial` state which only allows hiding based on metrics changes, after the first instance. Maybe there is a more elegant solution, but it works so far.

The Pull Request is here: #23

**Comment by appinteractive** [comment]
You can try my fix like this:

```yaml
el_tooltip:
    git:
      url: https://github.com/appinteractive/el_tooltip
      ref: a3f94d21fd0a0d3c3b9a9874152fdef79c2be622
```

**Comment by marcelogil** [comment]
Hello @aboodma . I have merged the changes made by @appinteractive.
This should be working now on version 2.1.0.
Please let me know if it's working for you.
