### ISSUE TITLE
Call the tooltip programatically

### ISSUE THREAD

**Issue by ench0** [marcelogil/el_tooltip#19]
Is there a way to call one of the tooltips programmatically? The use case would be to use this extension for an app tour; for example - the tooltip will pop up to explain a certain button, disappear after a few seconds (or tap) and then move on to another one. Another example will be to use it for short notifications that appear in specific parts of the app. Thanks in advance.

**Comment by marcelogil** [comment]
Hello @ench0 ,
To control the show/hide behaviour you can add a controller to each tooltip.
That way you can then make it appear and disappear when you want or when the timer tells it to.

Hope it helps
M

**Comment by ench0** [comment]
> Hello @ench0 , To control the show/hide behaviour you can add a controller to each tooltip. That way you can then make it appear and disappear when you want or when the timer tells it to.
> 
> Hope it helps M

Thanks so much, that's exactly what's needed, I was not aware of the controller feature. Keep it up!
