### ISSUE TITLE
Web Issue

### ISSUE THREAD

**Issue by Jaimin-BrightForce** [marcelogil/el_tooltip#21]
When I have hidden and dispose the tooltip, it will invisibly be opened in the center of my web. I can't see the UI but button clicks of my tooltip UI will work. So, In this case, I'm directly moving to other screens.

**Comment by marcelogil** [comment]
Hello @Jaimin-BrightForce 
I have just updated the package with a fix from @appinteractive that might be related to your issue.
Please let me know if it's working well for you on version 2.1.0.
