### ISSUE TITLE
controller.hide() not work

### ISSUE THREAD

**Issue by Paroca72** [marcelogil/el_tooltip#27]
Hello,

I trying to close the tooltip from the controller using _controller.hide() but it seems no have any effect.
Also _controller.notify(ElTooltipStatus.hidden) no have any effect.

Here how I initialize the tooltip:
```
ElTooltip(
            controller: _controller,
            content: _createTooltip(context, model),
            position: ElTooltipPosition.rightCenter,
            color: context.colorScheme.surfaceContainerHighest,
            child: next(),
          )
```

Thanks

**Comment by marcelogil** [comment]
@Paroca72 , can you try again with the new version 2.2.1?
Thanks!

**Comment by Paroca72** [comment]
Its seems OK now
Very thanks
