### ISSUE TITLE
Automatic positioning of tooltip

### ISSUE THREAD

**Issue by simplenotezy** [marcelogil/el_tooltip#8]
It would be cool if the tooltip could position itself according to the available screen

**Comment by marcelogil** [comment]
Hello @simplenotezy 
el_tooltip is already updating the position based on the screen size.
If you don't specify a default position it will do that automatically.

You can navigate to the folder example to see it working.
Just run: 

`flutter run -d chrome`

Hope it helps.

Cheers
Gil

**Comment by simplenotezy** [comment]
That's cool. I didn't notice position was nullable

**Comment by twocolors** [comment]
@marcelogil I think it's not working correctly

![image](https://github.com/marcelogil/el_tooltip/assets/207796/8dbda42a-f36d-426d-809f-6adcb5b1863a)
